export default {
  "title": "Nah Dah Dah Nah Nah (Opus 1984)",
  "subtitle":"Conway's Game of Life",
  "description": "This explorable is an implementation of Conway's Game of Life, one of the most famous cellular automata models for the emergence of structure, replication and complex behavior generated by simple rules."
}